apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  # Values are base64 encoded.
  # POSTGRES_PASSWORD=postgres -> cG9zdGdyZXM=
  # REPLICATION_PASSWORD=repl_password -> cmVwbF9wYXNzd29yZA==
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  REPLICATION_PASSWORD: cmVwbF9wYXNzd29yZA==
